default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:

development:
  <<: *default
  database: quiz_cards_api_db_dev

test:
  <<: *default
  database: quiz_cards_api_db_test

production:
  <<: *default
  host: <%= ENV['POSTGRESQL_HOST'] %>
  username: <%= ENV['POSTGRESQL_USER_NAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  database: <%= ENV['POSTGRESQL_DB'] %>
  port: <%= ENV['RDS_PORT'] %>
