default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  host: <%= ENV['POSTGRESQL_HOST'] %>
  username: <%= ENV['POSTGRESQL_USER_NAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  database: <%= ENV['POSTGRESQL_DB'] %>
